name: generate-api-types
on: [push]
jobs: 
  generate-types:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup node
        id: step1
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Generate hash of existing package
        id: step2
        run: |
          npm i json-schema-to-typescript
          npm i @deriv/types@latest
          echo ::set-output name=old_declarations_hash::"$(git hash-object ./node_modules/@deriv/types/output.d.ts)"

      - name: Generate declarations file from upstream
        id: step3
        run: |
          git clone https://github.com/binary-com/websockets.git
          cd websockets
          git checkout HEAD
          ../node_modules/.bin/json2ts --input "./config/v3/**/[!example]*.json" > index.d.ts
          echo ::set-output name=new_declarations_hash::"$(git hash-object index.d.ts)"

      - name: Generate new declarations file.
        id: step4
        run: |
          if [ ${{ steps.step2.outputs.old_declarations_hash }} = ${{ steps.step3.outputs.new_declarations_hash }} ]
          then
            echo "Hashes are the same. Aborting."
          else
            echo "Hashes are different. I will publish a new version."
          fi