name: generate-api-types
on: [push]
jobs: 
  generate-types:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      # - run: |
      #     chmod +x "${GITHUB_WORKSPACE}/.github/generate_types.sh"
      - run: |
          # Install dependencies
          sh ${GITHUB_WORKSPACE}/.github/generate_types.sh