name: generate-api-types
on: [push]
jobs: 
  generate-types:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: binary-com/websockets
          path: websockets
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: |
          # Install dependencies
          "${GITHUB_WORKSPACE}/.github/generate_types.sh