name: generate-api-types
on: [push]
jobs: 
  generate-types:
    runs-on: 'ubuntu-latest'
    steps:
      - id: step1
        uses: actions/checkout@v2

      - id: step2
        run: |
          ls && echo ::set-output name=declarations_hash::"${git hash-object}"

      - id: step3
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - id: step4
        run: |
          # Create a folder for the package that will be published.
          mkdir ./types

          # Checkout the upstream binary-com/websockets repo
          # and convert the JSON schema to TypeScript types/interfaces.
          git clone https://github.com/binary-com/websockets.git
          cd websockets
          git checkout HEAD

          # Convert schema to types/interfaces
          npm i json-schema-to-typescript
          ./node_modules/.bin/json2ts --input "./config/v3/**/[!example]*.json" > ../types/index.d.ts

          # Compare the hash of the new "index.d.t.s" with the existing one.
          git hash-object ../types/index.d.ts
          echo ${{ steps.step1.outputs.some_output }}