name: generate-api-types
on: [push]
jobs: 
  generate-types:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup node
        id: step1
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Generate hash of existing package
        id: step2
        run: |
          npm i @deriv/types@latest
          echo ::set-output name=declarations_hash::"$(git hash-object ./node_modules/@deriv/types/output.d.ts)"

      - name: Generate new declarations file.
        id: step3
        run: |
          echo ${{ steps.step2.outputs.declarations_hash }}
          mkdir ./types


          # Checkout the upstream binary-com/websockets repo
          # and convert the JSON schema to TypeScript types/interfaces.

          git clone https://github.com/binary-com/websockets.git
          cd websockets
          git checkout HEAD


          # Convert schema to types/interfaces

          npm i json-schema-to-typescript
          ls
          ./node_modules/.bin/json2ts --input "./config/v3/**/[!example]*.json" > ../types/index.d.ts


          # Compare the hash of the new "index.d.t.s" with the existing one.

          git hash-object ../types/index.d.ts
          echo ${{ steps.step2.outputs.declarations_hash }}